// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGamesStorage_Description_and_list_.Context;

#nullable disable

namespace VideoGamesStorage_Description_and_list_.Migrations
{
    [DbContext(typeof(ClassContext))]
    [Migration("20240619070612_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGamesStorage_Description_and_list_.Model.Games", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("AgeLimit")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("age_limit");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("NO ENTRIES");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("game_genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("game_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("platform");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("price");

                    b.HasKey("GameId")
                        .HasName("game_id");

                    b.ToTable("GameList", null, t =>
                        {
                            t.HasCheckConstraint("genreLimits", "game_genre = 'Action' OR game_genre = 'RPG' OR game_genre = 'Shooter' OR game_genre = 'Puzzle' OR game_genre = 'Simulator'");

                            t.HasCheckConstraint("platformLimits", "platform = 'Nintendo Switch' OR platform = 'Playstation 4' OR platform = 'Playstation 5' OR platform = 'PC' OR platform = 'Xbox One' ");

                            t.HasCheckConstraint("valueLimits", "age_limit= 'G' OR age_limit= 'PG' OR age_limit= 'PG-13' OR age_limit= 'R' OR age_limit= 'NC-17' ");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
